lang: ja
theme: jekyll-theme-cayman
show_downloads: false
title: 音訳グループ やまびこ
description: 東京都北区を中心に活動する ボランティアグループ
markdown: kramdown
collections:
  tusin:
    output: true
    permalink: :title.html
  info:
    output: true
    permalink: :title.html
