lang: ja
theme: jekyll-theme-primer
show_downloads: false
title: 音訳グループ やまびこ
description: 東京都北区を中心に活動している ボランティアグループです。
markdown: kramdown
collections:
  tusin:
    output: true
    permalink: :title.html
