lang: ja
theme: jekyll-theme-cayman
show_downloads: false
title: 音訳グループ やまびこ
logo: /icons/android-chrome-512x512.png
markdown: kramdown
plugins:
 - jekyll-sitemap
collections:
  tusin:
    output: true
    permalink: :title.html
  info:
    output: true
    permalink: :title.html
  p:
    output: true
    permalink: /p/:title.html    
