lang: ja
theme: jekyll-theme-cayman
show_downloads: false
title: false
markdown: kramdown
collections:
  tusin:
    output: true
    permalink: :title.html
  info:
    output: true
    permalink: :title.html
  p:
    output: true
    permalink: /p/:title.html    
